package:
  name: ros-noetic-move-base-flex
  version: 0.4.0
source:
  git_url: https://github.com/uos-gbp/move_base_flex-release.git
  git_rev: release/noetic/move_base_flex/0.4.0-1
  folder: ros-noetic-move-base-flex/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-mbf-abstract-core
    - ros-noetic-mbf-abstract-nav
    - ros-noetic-mbf-costmap-core
    - ros-noetic-mbf-costmap-nav
    - ros-noetic-mbf-msgs
    - ros-noetic-mbf-simple-nav
    - ros-noetic-mbf-utility
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
