package:
  name: ros-noetic-jsk-pcl-ros-utils
  version: 1.2.15
source:
  git_url: https://github.com/tork-a/jsk_recognition-release.git
  git_rev: release/noetic/jsk_pcl_ros_utils/1.2.15-1
  folder: ros-noetic-jsk-pcl-ros-utils/src/work
  patches:
    - patch/ros-noetic-jsk-pcl-ros-utils.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(unix): "{{ cdt('mesa-libgl-devel') }}"
    - sel(unix): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - boost
    - python
    - pyyaml
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-diagnostic-msgs
    - ros-noetic-diagnostic-updater
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-eigen-conversions
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-transport
    - ros-noetic-image-view2
    - ros-noetic-interactive-markers
    - ros-noetic-jsk-data
    - ros-noetic-jsk-footstep-msgs
    - ros-noetic-jsk-recognition-msgs
    - ros-noetic-jsk-recognition-utils
    - ros-noetic-jsk-tools
    - ros-noetic-jsk-topic-tools
    - ros-noetic-kdl-conversions
    - ros-noetic-kdl-parser
    - ros-noetic-laser-assembler
    - ros-noetic-message-generation
    - ros-noetic-moveit-core
    - ros-noetic-moveit-ros-perception
    - ros-noetic-nav-msgs
    - ros-noetic-nodelet
    - ros-noetic-octomap
    - ros-noetic-octomap-msgs
    - ros-noetic-octomap-ros
    - ros-noetic-octomap-server
    - ros-noetic-pcl-conversions
    - ros-noetic-pcl-msgs
    - ros-noetic-pcl-ros
    - ros-noetic-robot-self-filter
    - ros-noetic-rosboost-cfg
    - ros-noetic-roscpp-tutorials
    - ros-noetic-roslaunch
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-stereo-msgs
    - ros-noetic-tf
    - ros-noetic-tf-conversions
    - ros-noetic-tf2-ros
    - ros-noetic-visualization-msgs
    - yaml-cpp
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-compressed-depth-image-transport
    - ros-noetic-compressed-image-transport
    - ros-noetic-cv-bridge
    - ros-noetic-diagnostic-msgs
    - ros-noetic-diagnostic-updater
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-eigen-conversions
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-transport
    - ros-noetic-image-view
    - ros-noetic-image-view2
    - ros-noetic-interactive-markers
    - ros-noetic-jsk-data
    - ros-noetic-jsk-footstep-msgs
    - ros-noetic-jsk-recognition-msgs
    - ros-noetic-jsk-recognition-utils
    - ros-noetic-jsk-rviz-plugins
    - ros-noetic-jsk-topic-tools
    - ros-noetic-kdl-conversions
    - ros-noetic-kdl-parser
    - ros-noetic-laser-assembler
    - ros-noetic-message-runtime
    - ros-noetic-moveit-core
    - ros-noetic-moveit-ros-perception
    - ros-noetic-nav-msgs
    - ros-noetic-nodelet
    - ros-noetic-octomap
    - ros-noetic-octomap-msgs
    - ros-noetic-octomap-ros
    - ros-noetic-octomap-server
    - ros-noetic-openni2-launch
    - ros-noetic-pcl-conversions
    - ros-noetic-pcl-msgs
    - ros-noetic-pcl-ros
    - ros-noetic-robot-self-filter
    - ros-noetic-rosbag
    - ros-noetic-rosboost-cfg
    - ros-noetic-roscpp-tutorials
    - ros-noetic-rviz
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-stereo-msgs
    - ros-noetic-tf
    - ros-noetic-tf-conversions
    - ros-noetic-tf2-ros
    - ros-noetic-visualization-msgs
    - scikit-learn
    - yaml-cpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
