package:
  name: ros-noetic-toposens
  version: 2.3.0
source:
  git_url: https://gitlab.com/toposens/public/toposens-release.git
  git_rev: release/noetic/toposens/2.3.0-1
  folder: ros-noetic-toposens/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-toposens-bringup
    - ros-noetic-toposens-description
    - ros-noetic-toposens-driver
    - ros-noetic-toposens-echo-driver
    - ros-noetic-toposens-markers
    - ros-noetic-toposens-msgs
    - ros-noetic-toposens-pointcloud
    - ros-noetic-toposens-sync
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
