package:
  name: ros-noetic-sparse-bundle-adjustment
  version: 0.4.4
source:
  git_url: https://github.com/ros-gbp/sparse_bundle_adjustment-release.git
  git_rev: release/noetic/sparse_bundle_adjustment/0.4.4-1
  folder: ros-noetic-sparse-bundle-adjustment/src/work
  patches:
    - patch/ros-noetic-sparse-bundle-adjustment.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - eigen
    - libblas
    - libcblas
    - liblapack
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-roscpp
    - suitesparse
  run:
    - eigen
    - libblas
    - libcblas
    - liblapack
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-roscpp
    - suitesparse
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
