package:
  name: ros-noetic-moveit-servo
  version: 1.1.5
source:
  git_url: https://github.com/ros-gbp/moveit-release.git
  git_rev: release/noetic/moveit_servo/1.1.5-1
  folder: ros-noetic-moveit-servo/src/work
  patches:
    - patch/ros-noetic-moveit-servo.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-control-msgs
    - ros-noetic-control-toolbox
    - ros-noetic-geometry-msgs
    - ros-noetic-moveit-msgs
    - ros-noetic-moveit-resources-panda-moveit-config
    - ros-noetic-moveit-ros-planning-interface
    - ros-noetic-rosparam-shortcuts
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf2-eigen
    - ros-noetic-trajectory-msgs
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-control-msgs
    - ros-noetic-control-toolbox
    - ros-noetic-geometry-msgs
    - ros-noetic-joy-teleop
    - ros-noetic-moveit-msgs
    - ros-noetic-moveit-ros-planning-interface
    - ros-noetic-rosparam-shortcuts
    - ros-noetic-sensor-msgs
    - ros-noetic-spacenav-node
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf2-eigen
    - ros-noetic-trajectory-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
