package:
  name: ros-noetic-image-publisher
  version: 1.15.3
source:
  git_url: https://github.com/ros-gbp/image_pipeline-release.git
  git_rev: release/noetic/image_publisher/1.15.3-1
  folder: ros-noetic-image-publisher/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-camera-info-manager
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-transport
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-camera-info-manager
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-transport
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
