package:
  name: ros-noetic-pilz-control
  version: 0.6.0
source:
  git_url: https://github.com/PilzDE/pilz_robots-release.git
  git_rev: release/noetic/pilz_control/0.6.0-1
  folder: ros-noetic-pilz-control/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-code-coverage
    - ros-noetic-controller-interface
    - ros-noetic-controller-manager
    - ros-noetic-geometry-msgs
    - ros-noetic-joint-trajectory-controller
    - ros-noetic-moveit-core
    - ros-noetic-moveit-ros-planning
    - ros-noetic-pilz-msgs
    - ros-noetic-pilz-testutils
    - ros-noetic-pilz-utils
    - ros-noetic-roscpp
    - ros-noetic-roslint
    - ros-noetic-rostest
    - ros-noetic-rosunit
    - ros-noetic-std-srvs
    - ros-noetic-tf2
    - ros-noetic-tf2-geometry-msgs
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-controller-interface
    - ros-noetic-controller-manager
    - ros-noetic-joint-trajectory-controller
    - ros-noetic-moveit-core
    - ros-noetic-moveit-ros-planning
    - ros-noetic-pilz-msgs
    - ros-noetic-roscpp
    - ros-noetic-std-srvs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
