package:
  name: ros-noetic-bondcpp
  version: 1.8.6
source:
  git_url: https://github.com/ros-gbp/bond_core-release.git
  git_rev: release/noetic/bondcpp/1.8.6-1
  folder: ros-noetic-bondcpp/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - boost-cpp
    - libuuid
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-bond
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-roscpp
    - ros-noetic-smclib
  run:
    - boost-cpp
    - libuuid
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-bond
    - ros-noetic-roscpp
    - ros-noetic-smclib
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
