package:
  name: ros-noetic-grid-map
  version: 1.6.4
source:
  git_url: https://github.com/anybotics/grid_map-release.git
  git_rev: release/noetic/grid_map/1.6.4-1
  folder: ros-noetic-grid-map/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-grid-map-core
    - ros-noetic-grid-map-cv
    - ros-noetic-grid-map-demos
    - ros-noetic-grid-map-filters
    - ros-noetic-grid-map-loader
    - ros-noetic-grid-map-msgs
    - ros-noetic-grid-map-ros
    - ros-noetic-grid-map-rviz-plugin
    - ros-noetic-grid-map-visualization
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
