package:
  name: ros-noetic-cob-navigation
  version: 0.6.11
source:
  git_url: https://github.com/ipa320/cob_navigation-release.git
  git_rev: release/noetic/cob_navigation/0.6.11-1
  folder: ros-noetic-cob-navigation/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-cob-linear-nav
    - ros-noetic-cob-map-accessibility-analysis
    - ros-noetic-cob-mapping-slam
    - ros-noetic-cob-navigation-config
    - ros-noetic-cob-navigation-global
    - ros-noetic-cob-navigation-local
    - ros-noetic-cob-navigation-slam
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
