package:
  name: ros-noetic-jsk-rviz-plugins
  version: 2.1.7
source:
  git_url: https://github.com/tork-a/jsk_visualization-release.git
  git_rev: release/noetic/jsk_rviz_plugins/2.1.7-4
  folder: ros-noetic-jsk-rviz-plugins/src/work
  patches:
    - patch/ros-noetic-jsk-rviz-plugins.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(unix): "{{ cdt('mesa-libgl-devel') }}"
    - sel(unix): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-diagnostic-msgs
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-jsk-footstep-msgs
    - ros-noetic-jsk-gui-msgs
    - ros-noetic-jsk-hark-msgs
    - ros-noetic-jsk-recognition-msgs
    - ros-noetic-jsk-recognition-utils
    - ros-noetic-jsk-topic-tools
    - ros-noetic-message-generation
    - ros-noetic-mk
    - ros-noetic-people-msgs
    - ros-noetic-rosbuild
    - ros-noetic-rviz
    - ros-noetic-std-msgs
    - ros-noetic-urdfdom-py
    - ros-noetic-view-controller-msgs
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-cv-bridge
    - ros-noetic-diagnostic-msgs
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-publisher
    - ros-noetic-jsk-footstep-msgs
    - ros-noetic-jsk-gui-msgs
    - ros-noetic-jsk-hark-msgs
    - ros-noetic-jsk-recognition-msgs
    - ros-noetic-jsk-recognition-utils
    - ros-noetic-jsk-topic-tools
    - ros-noetic-message-generation
    - ros-noetic-people-msgs
    - ros-noetic-posedetection-msgs
    - ros-noetic-rviz
    - ros-noetic-std-msgs
    - ros-noetic-urdfdom-py
    - ros-noetic-view-controller-msgs
    - scipy
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
