package:
  name: ros-noetic-map-laser
  version: 0.0.5
source:
  git_url: https://github.com/wu-robotics/laser_filtering_release.git
  git_rev: release/noetic/map_laser/0.0.5-1
  folder: ros-noetic-map-laser/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-nav-msgs
    - ros-noetic-roslaunch
    - ros-noetic-roslint
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-laser-filters
    - ros-noetic-nav-msgs
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
