package:
  name: ros-noetic-industrial-robot-simulator
  version: 0.7.2
source:
  git_url: https://github.com/ros-industrial-release/industrial_core-release.git
  git_rev: release/noetic/industrial_robot_simulator/0.7.2-1
  folder: ros-noetic-industrial-robot-simulator/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-roslaunch
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-control-msgs
    - ros-noetic-industrial-msgs
    - ros-noetic-industrial-robot-client
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-trajectory-msgs
    - rospkg
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
