package:
  name: ros-noetic-checkerboard-detector
  version: 1.2.15
source:
  git_url: https://github.com/tork-a/jsk_recognition-release.git
  git_rev: release/noetic/checkerboard_detector/1.2.15-1
  folder: ros-noetic-checkerboard-detector/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(unix): "{{ cdt('mesa-libgl-devel') }}"
    - sel(unix): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-dynamic-tf-publisher
    - ros-noetic-eigen-conversions
    - ros-noetic-image-geometry
    - ros-noetic-image-publisher
    - ros-noetic-jsk-recognition-msgs
    - ros-noetic-jsk-tools
    - ros-noetic-jsk-topic-tools
    - ros-noetic-message-filters
    - ros-noetic-posedetection-msgs
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - ros-noetic-tf2
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-cv-bridge
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-dynamic-tf-publisher
    - ros-noetic-eigen-conversions
    - ros-noetic-image-geometry
    - ros-noetic-image-publisher
    - ros-noetic-jsk-recognition-msgs
    - ros-noetic-message-filters
    - ros-noetic-posedetection-msgs
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - ros-noetic-tf2
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
