package:
  name: ros-noetic-roboticsgroup-upatras-gazebo-plugins
  version: 0.2.0
source:
  git_url: https://github.com/roboticsgroup/roboticsgroup_upatras_gazebo_plugins-release.git
  git_rev: release/noetic/roboticsgroup_upatras_gazebo_plugins/0.2.0-2
  folder: ros-noetic-roboticsgroup-upatras-gazebo-plugins/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-control-toolbox
    - ros-noetic-gazebo-ros
    - ros-noetic-roscpp
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-control-toolbox
    - ros-noetic-gazebo-ros
    - ros-noetic-roscpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
