package:
  name: ros-noetic-volta-navigation
  version: 1.2.0
source:
  git_url: https://github.com/botsync-gbp/volta-release.git
  git_rev: release/noetic/volta_navigation/1.2.0-1
  folder: ros-noetic-volta-navigation/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-amcl
    - ros-noetic-dwa-local-planner
    - ros-noetic-global-planner
    - ros-noetic-gmapping
    - ros-noetic-map-server
    - ros-noetic-move-base
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
