package:
  name: ros-noetic-turtlebot3-gazebo
  version: 1.3.2
source:
  git_url: https://github.com/ROBOTIS-GIT-release/turtlebot3_simulations-release.git
  git_rev: release/noetic/turtlebot3_gazebo/1.3.2-2
  folder: ros-noetic-turtlebot3-gazebo/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-gazebo-ros
    - ros-noetic-geometry-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
  run:
    - gazebo
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-gazebo-ros
    - ros-noetic-geometry-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-turtlebot3-description
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
