package:
  name: ros-noetic-swri-image-util
  version: 2.14.2
source:
  git_url: https://github.com/swri-robotics-gbp/marti_common-release.git
  git_rev: release/noetic/swri_image_util/2.14.2-1
  folder: ros-noetic-swri-image-util/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
    - sel(unix): "{{ cdt('mesa-libgl-devel') }}"
    - sel(unix): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - boost
    - eigen
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-camera-calibration-parsers
    - ros-noetic-catkin
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-nav-msgs
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-rostest
    - ros-noetic-std-msgs
    - ros-noetic-swri-geometry-util
    - ros-noetic-swri-math-util
    - ros-noetic-swri-nodelet
    - ros-noetic-swri-opencv-util
    - ros-noetic-swri-roscpp
    - ros-noetic-tf
    - sel(build_platform == target_platform): pkg-config
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - boost
    - eigen
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-camera-calibration-parsers
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-image-geometry
    - ros-noetic-image-transport
    - ros-noetic-message-filters
    - ros-noetic-nav-msgs
    - ros-noetic-nodelet
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-std-msgs
    - ros-noetic-swri-geometry-util
    - ros-noetic-swri-math-util
    - ros-noetic-swri-opencv-util
    - ros-noetic-swri-roscpp
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
