package:
  name: ros-noetic-geographic-msgs
  version: 0.5.6
source:
  git_url: https://github.com/ros-geographic-info/geographic_info-release.git
  git_rev: release/noetic/geographic_msgs/0.5.6-1
  folder: ros-noetic-geographic-msgs/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-std-msgs
    - ros-noetic-uuid-msgs
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-message-runtime
    - ros-noetic-std-msgs
    - ros-noetic-uuid-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
