package:
  name: ros-noetic-nodelet-topic-tools
  version: 1.10.2
source:
  git_url: https://github.com/ros-gbp/nodelet_core-release.git
  git_rev: release/noetic/nodelet_topic_tools/1.10.2-1
  folder: ros-noetic-nodelet-topic-tools/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
  run:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-message-filters
    - ros-noetic-nodelet
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
