package:
  name: ros-noetic-flexbe-behavior-engine
  version: 1.3.1
source:
  git_url: https://github.com/FlexBE/flexbe_behavior_engine-release.git
  git_rev: release/noetic/flexbe_behavior_engine/1.3.1-1
  folder: ros-noetic-flexbe-behavior-engine/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-flexbe-core
    - ros-noetic-flexbe-input
    - ros-noetic-flexbe-mirror
    - ros-noetic-flexbe-msgs
    - ros-noetic-flexbe-onboard
    - ros-noetic-flexbe-states
    - ros-noetic-flexbe-testing
    - ros-noetic-flexbe-widget
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
