package:
  name: ros-noetic-neonavigation
  version: 0.11.0
source:
  git_url: https://github.com/at-wat/neonavigation-release.git
  git_rev: release/noetic/neonavigation/0.11.0-1
  folder: ros-noetic-neonavigation/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-costmap-cspace
    - ros-noetic-joystick-interrupt
    - ros-noetic-map-organizer
    - ros-noetic-neonavigation-common
    - ros-noetic-neonavigation-launch
    - ros-noetic-obj-to-pointcloud
    - ros-noetic-planner-cspace
    - ros-noetic-safety-limiter
    - ros-noetic-track-odometry
    - ros-noetic-trajectory-tracker
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
