package:
  name: ros-noetic-open-manipulator-gazebo
  version: 1.1.1
source:
  git_url: https://github.com/ROBOTIS-GIT-release/open_manipulator_simulations-release.git
  git_rev: release/noetic/open_manipulator_gazebo/1.1.1-1
  folder: ros-noetic-open-manipulator-gazebo/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-controller-manager
    - ros-noetic-gazebo-ros
    - ros-noetic-gazebo-ros-control
    - ros-noetic-roscpp
    - ros-noetic-std-msgs
    - ros-noetic-urdf
    - ros-noetic-xacro
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-controller-manager
    - ros-noetic-gazebo-ros
    - ros-noetic-gazebo-ros-control
    - ros-noetic-roscpp
    - ros-noetic-std-msgs
    - ros-noetic-urdf
    - ros-noetic-xacro
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
