package:
  name: ros-noetic-explore-lite
  version: 2.1.4
source:
  git_url: https://github.com/hrnr/m-explore-release.git
  git_rev: release/noetic/explore_lite/2.1.4-1
  folder: ros-noetic-explore-lite/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-catkin
    - ros-noetic-costmap-2d
    - ros-noetic-geometry-msgs
    - ros-noetic-map-msgs
    - ros-noetic-move-base-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-roslaunch
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-visualization-msgs
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-costmap-2d
    - ros-noetic-geometry-msgs
    - ros-noetic-map-msgs
    - ros-noetic-move-base-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-visualization-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
