package:
  name: ros-noetic-jsk-tilt-laser
  version: 2.2.11
source:
  git_url: https://github.com/tork-a/jsk_common-release.git
  git_rev: release/noetic/jsk_tilt_laser/2.2.11-2
  folder: ros-noetic-jsk-tilt-laser/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-laser-assembler
    - ros-noetic-laser-filters
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - ros-noetic-tf-conversions
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-laser-assembler
    - ros-noetic-laser-filters
    - ros-noetic-robot-state-publisher
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - ros-noetic-tf-conversions
    - ros-noetic-urg-node
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
