package:
  name: ros-noetic-respeaker-ros
  version: 2.1.21
source:
  git_url: https://github.com/tork-a/jsk_3rdparty-release.git
  git_rev: release/noetic/respeaker_ros/2.1.21-2
  folder: ros-noetic-respeaker-ros/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-jsk-tools
  run:
    - libflac
    - python
    - pyusb
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-angles
    - ros-noetic-audio-common-msgs
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-geometry-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - speechrecognition
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
