package:
  name: ros-noetic-pointgrey-camera-description
  version: 0.15.0
source:
  git_url: https://github.com/ros-drivers-gbp/pointgrey_camera_driver-release.git
  git_rev: release/noetic/pointgrey_camera_description/0.15.0-1
  folder: ros-noetic-pointgrey-camera-description/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-robot-state-publisher
    - ros-noetic-urdf
    - ros-noetic-xacro
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
