package:
  name: ros-noetic-moveit-commander
  version: 1.1.5
source:
  git_url: https://github.com/ros-gbp/moveit-release.git
  git_rev: release/noetic/moveit_commander/1.1.5-1
  folder: ros-noetic-moveit-commander/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - catkin_pkg
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-moveit-resources-fanuc-moveit-config
    - ros-noetic-rostest
  run:
    - assimp
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-moveit-msgs
    - ros-noetic-moveit-ros-planning-interface
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-shape-msgs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
