package:
  name: ros-noetic-webots-ros
  version: 4.1.0
source:
  git_url: https://github.com/cyberbotics/webots_ros-release.git
  git_rev: release/noetic/webots_ros/4.1.0-1
  folder: ros-noetic-webots-ros/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-moveit-ros-planning-interface
    - ros-noetic-robot-state-publisher
    - ros-noetic-ros-control
    - ros-noetic-ros-controllers
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-message-runtime
    - ros-noetic-moveit-ros-planning-interface
    - ros-noetic-robot-state-publisher
    - ros-noetic-ros-control
    - ros-noetic-ros-controllers
    - ros-noetic-roscpp
    - ros-noetic-rospy
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
