package:
  name: ros-noetic-srdfdom
  version: 0.6.2
source:
  git_url: https://github.com/ros-gbp/srdfdom-release.git
  git_rev: release/noetic/srdfdom/0.6.2-1
  folder: ros-noetic-srdfdom/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - boost
    - console_bridge
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-rostest
    - ros-noetic-urdf
    - tinyxml2
  run:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-urdf
    - ros-noetic-urdfdom-py
    - tinyxml2
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
