package:
  name: ros-noetic-moveit-python
  version: 0.4.2
source:
  git_url: https://github.com/mikeferguson/moveit_python-release.git
  git_rev: release/noetic/moveit_python/0.4.2-1
  folder: ros-noetic-moveit-python/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - assimp
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-geometry-msgs
    - ros-noetic-moveit-msgs
    - ros-noetic-rospy
    - ros-noetic-shape-msgs
    - ros-noetic-tf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
