package:
  name: ros-noetic-resource-retriever
  version: 1.12.6
source:
  git_url: https://github.com/ros-gbp/resource_retriever-release.git
  git_rev: release/noetic/resource_retriever/1.12.6-1
  folder: ros-noetic-resource-retriever/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - boost
    - libcurl
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-rosconsole
    - ros-noetic-roslib
  run:
    - boost
    - libcurl
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-rosconsole
    - ros-noetic-roslib
    - rospkg
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
