package:
  name: ros-noetic-qt-gui
  version: 0.4.2
source:
  git_url: https://github.com/ros-gbp/qt_gui_core-release.git
  git_rev: release/noetic/qt_gui/0.4.2-1
  folder: ros-noetic-qt-gui/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - pyqt 5.12
    - python
    - qt 5.12
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - setuptools
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-python-qt-binding
    - rospkg
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
