package:
  name: ros-noetic-mir-navigation
  version: 1.1.3
source:
  git_url: https://github.com/uos-gbp/mir_robot-release.git
  git_rev: release/noetic/mir_navigation/1.1.3-1
  folder: ros-noetic-mir-navigation/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-roslaunch
  run:
    - matplotlib-base
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-amcl
    - ros-noetic-base-local-planner
    - ros-noetic-dwa-local-planner
    - ros-noetic-dwb-critics
    - ros-noetic-dwb-local-planner
    - ros-noetic-dwb-plugins
    - ros-noetic-hector-mapping
    - ros-noetic-map-server
    - ros-noetic-mir-driver
    - ros-noetic-mir-dwb-critics
    - ros-noetic-mir-gazebo
    - ros-noetic-move-base
    - ros-noetic-nav-core-adapter
    - ros-noetic-sbpl-lattice-planner
    - ros-noetic-teb-local-planner
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
