package:
  name: ros-noetic-cob-grasp-generation
  version: 0.7.5
source:
  git_url: https://github.com/ipa320/cob_manipulation-release.git
  git_rev: release/noetic/cob_grasp_generation/0.7.5-1
  folder: ros-noetic-cob-grasp-generation/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib-msgs
    - ros-noetic-catkin
    - ros-noetic-message-generation
    - ros-noetic-moveit-msgs
    - setuptools
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-cob-description
    - ros-noetic-geometry-msgs
    - ros-noetic-message-runtime
    - ros-noetic-moveit-msgs
    - ros-noetic-robot-state-publisher
    - ros-noetic-roslib
    - ros-noetic-rospy
    - ros-noetic-rviz
    - ros-noetic-schunk-description
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-ros
    - ros-noetic-trajectory-msgs
    - ros-noetic-visualization-msgs
    - ros-noetic-xacro
    - scipy
    - six
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
