package:
  name: ros-noetic-turtlebot3-bringup
  version: 1.2.5
source:
  git_url: https://github.com/ROBOTIS-GIT-release/turtlebot3-release.git
  git_rev: release/noetic/turtlebot3_bringup/1.2.5-1
  folder: ros-noetic-turtlebot3-bringup/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-diagnostic-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-turtlebot3-msgs
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-diagnostic-msgs
    - ros-noetic-hls-lfcd-lds-driver
    - ros-noetic-joint-state-publisher
    - ros-noetic-robot-state-publisher
    - ros-noetic-roscpp
    - ros-noetic-rosserial-python
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-turtlebot3-description
    - ros-noetic-turtlebot3-msgs
    - ros-noetic-turtlebot3-teleop
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
