package:
  name: ros-noetic-virtual-force-publisher
  version: 2.2.11
source:
  git_url: https://github.com/tork-a/jsk_common-release.git
  git_rev: release/noetic/virtual_force_publisher/2.2.11-2
  folder: ros-noetic-virtual-force-publisher/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-kdl-parser
    - ros-noetic-sensor-msgs
    - ros-noetic-tf-conversions
    - ros-noetic-urdf
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-geometry-msgs
    - ros-noetic-kdl-parser
    - ros-noetic-sensor-msgs
    - ros-noetic-tf-conversions
    - ros-noetic-urdf
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
