package:
  name: ros-noetic-laser-filters-jsk-patch
  version: 2.1.21
source:
  git_url: https://github.com/tork-a/jsk_3rdparty-release.git
  git_rev: release/noetic/laser_filters_jsk_patch/2.1.21-2
  folder: ros-noetic-laser-filters-jsk-patch/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - git
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cmake-modules
    - ros-noetic-filters
    - ros-noetic-laser-filters
    - ros-noetic-laser-geometry
    - ros-noetic-mk
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-filters
    - ros-noetic-laser-filters
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
