package:
  name: ros-noetic-rosserial-arduino
  version: 0.9.2
source:
  git_url: https://github.com/ros-gbp/rosserial-release.git
  git_rev: release/noetic/rosserial_arduino/0.9.2-1
  folder: ros-noetic-rosserial-arduino/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-message-generation
    - ros-noetic-message-runtime
    - ros-noetic-rospy
    - ros-noetic-rosserial-client
    - ros-noetic-rosserial-msgs
    - ros-noetic-rosserial-python
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-message-runtime
    - ros-noetic-rospy
    - ros-noetic-rosserial-client
    - ros-noetic-rosserial-msgs
    - ros-noetic-rosserial-python
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
