package:
  name: ros-noetic-diagnostics
  version: 1.10.4
source:
  git_url: https://github.com/ros-gbp/diagnostics-release.git
  git_rev: release/noetic/diagnostics/1.10.4-1
  folder: ros-noetic-diagnostics/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 1
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diagnostic-analysis
    - ros-noetic-diagnostic-common-diagnostics
    - ros-noetic-diagnostic-updater
    - ros-noetic-self-test
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-diagnostic-aggregator
    - ros-noetic-diagnostic-analysis
    - ros-noetic-diagnostic-common-diagnostics
    - ros-noetic-diagnostic-updater
    - ros-noetic-self-test
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
