package:
  name: ros-noetic-rqt-topic
  version: 0.4.12
source:
  git_url: https://github.com/ros-gbp/rqt_topic-release.git
  git_rev: release/noetic/rqt_topic/0.4.12-1
  folder: ros-noetic-rqt-topic/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-python-qt-binding
    - ros-noetic-rostopic
    - ros-noetic-rqt-gui
    - ros-noetic-rqt-gui-py
    - ros-noetic-std-msgs
    - rospkg
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
