package:
  name: ros-noetic-hls-lfcd-lds-driver
  version: 1.1.2
source:
  git_url: https://github.com/ROBOTIS-GIT-release/hls-lfcd-lds-driver-release.git
  git_rev: release/noetic/hls_lfcd_lds_driver/1.1.2-1
  folder: ros-noetic-hls-lfcd-lds-driver/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
  run:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
