package:
  name: ros-noetic-jsk-data
  version: 2.2.11
source:
  git_url: https://github.com/tork-a/jsk_common-release.git
  git_rev: release/noetic/jsk_data/2.2.11-2
  folder: ros-noetic-jsk-data/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - freezegun
    - imageio
    - nose
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-message-generation
    - ros-noetic-roslaunch
    - ros-noetic-roslint
    - ros-noetic-rostest
  run:
    - click
    - gdown
    - paramiko
    - python
    - pyyaml
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-depth-image-proc
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-image-transport
    - ros-noetic-jsk-topic-tools
    - ros-noetic-message-runtime
    - ros-noetic-nodelet
    - ros-noetic-rosbag
    - ros-noetic-rqt-bag
    - ros-noetic-rviz
    - ros-noetic-tf2-ros
    - ros-noetic-xacro
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
