package:
  name: ros-noetic-cob-collision-monitor
  version: 0.7.5
source:
  git_url: https://github.com/ipa320/cob_manipulation-release.git
  git_rev: release/noetic/cob_collision_monitor/0.7.5-1
  folder: ros-noetic-cob-collision-monitor/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-moveit-ros-move-group
    - ros-noetic-moveit-ros-planning
    - ros-noetic-pluginlib
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-ros
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-cob-moveit-config
    - ros-noetic-moveit-ros-move-group
    - ros-noetic-moveit-ros-planning
    - ros-noetic-pluginlib
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-ros
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
