package:
  name: ros-noetic-moveit-kinematics
  version: 1.1.5
source:
  git_url: https://github.com/ros-gbp/moveit-release.git
  git_rev: release/noetic/moveit_kinematics/1.1.5-1
  folder: ros-noetic-moveit-kinematics/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - eigen
    - orocos-kdl
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-moveit-core
    - ros-noetic-moveit-resources-fanuc-description
    - ros-noetic-moveit-resources-fanuc-moveit-config
    - ros-noetic-moveit-resources-panda-description
    - ros-noetic-moveit-resources-panda-moveit-config
    - ros-noetic-moveit-ros-planning
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - ros-noetic-rostest
    - ros-noetic-tf2
    - ros-noetic-tf2-kdl
    - ros-noetic-xmlrpcpp
  run:
    - eigen
    - lxml
    - orocos-kdl
    - python
    - pyyaml
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-moveit-core
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - ros-noetic-tf2
    - ros-noetic-tf2-kdl
    - urdfdom
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
