package:
  name: ros-noetic-robot-upstart
  version: 0.4.1
source:
  git_url: https://github.com/clearpath-gbp/robot_upstart-release.git
  git_rev: release/noetic/robot_upstart/0.4.1-1
  folder: ros-noetic-robot-upstart/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-roslint
    - ros-noetic-rosunit
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-roslaunch
    - ros-noetic-xacro
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
