package:
  name: ros-noetic-pr2-head-action
  version: 1.10.18
source:
  git_url: https://github.com/pr2-gbp/pr2_controllers-release.git
  git_rev: release/noetic/pr2_head_action/1.10.18-1
  folder: ros-noetic-pr2-head-action/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - orocos-kdl
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-catkin
    - ros-noetic-geometry-msgs
    - ros-noetic-kdl-parser
    - ros-noetic-message-filters
    - ros-noetic-pr2-controllers-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - ros-noetic-tf-conversions
    - ros-noetic-trajectory-msgs
  run:
    - orocos-kdl
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-geometry-msgs
    - ros-noetic-kdl-parser
    - ros-noetic-message-filters
    - ros-noetic-pr2-controllers-msgs
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-tf
    - ros-noetic-tf-conversions
    - ros-noetic-trajectory-msgs
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
