package:
  name: ros-noetic-moveit-setup-assistant
  version: 1.1.5
source:
  git_url: https://github.com/ros-gbp/moveit-release.git
  git_rev: release/noetic/moveit_setup_assistant/1.1.5-1
  folder: ros-noetic-moveit-setup-assistant/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(unix): "{{ cdt('mesa-libgl-devel') }}"
    - sel(unix): "{{ cdt('mesa-dri-drivers') }}"
    - sel(linux): "{{ cdt('libselinux') }}"
    - sel(linux): "{{ cdt('libxdamage') }}"
    - sel(linux): "{{ cdt('libxxf86vm') }}"
    - sel(linux): "{{ cdt('libxfixes') }}"
    - sel(linux): "{{ cdt('libxext') }}"
    - sel(linux): "{{ cdt('libxau') }}"
    - sel(linux): "{{ cdt('libxcb') }}"
  host:
    - ogre
    - python
    - qt 5.12
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-moveit-core
    - ros-noetic-moveit-resources-panda-moveit-config
    - ros-noetic-moveit-ros-planning
    - ros-noetic-moveit-ros-visualization
    - ros-noetic-ompl
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rosunit
    - ros-noetic-rviz
    - ros-noetic-srdfdom
    - ros-noetic-urdf
    - yaml-cpp
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-moveit-core
    - ros-noetic-moveit-ros-planning
    - ros-noetic-moveit-ros-visualization
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-rviz
    - ros-noetic-srdfdom
    - ros-noetic-urdf
    - ros-noetic-xacro
    - yaml-cpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
    - sel(unix): xorg-libx11
    - sel(unix): xorg-libxext
