package:
  name: ros-noetic-pose-follower
  version: 0.3.4
source:
  git_url: https://github.com/ros-gbp/navigation_experimental-release.git
  git_rev: release/noetic/pose_follower/0.3.4-1
  folder: ros-noetic-pose-follower/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-base-local-planner
    - ros-noetic-catkin
    - ros-noetic-costmap-2d
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-nav-core
    - ros-noetic-nav-msgs
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-base-local-planner
    - ros-noetic-costmap-2d
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-nav-core
    - ros-noetic-nav-msgs
    - ros-noetic-pluginlib
    - ros-noetic-roscpp
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
