package:
  name: ros-noetic-camera-calibration-parsers
  version: 1.12.0
source:
  git_url: https://github.com/ros-gbp/image_common-release.git
  git_rev: release/noetic/camera_calibration_parsers/1.12.0-1
  folder: ros-noetic-camera-calibration-parsers/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 6
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
    - sel(build_platform != target_platform): pkg-config
  host:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-rosbash
    - ros-noetic-rosconsole
    - ros-noetic-roscpp
    - ros-noetic-roscpp-serialization
    - ros-noetic-rosunit
    - ros-noetic-sensor-msgs
    - yaml-cpp
    - sel(build_platform == target_platform): pkg-config
  run:
    - boost
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-roscpp
    - ros-noetic-roscpp-serialization
    - ros-noetic-sensor-msgs
    - yaml-cpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
