package:
  name: ros-noetic-cob-gazebo-worlds
  version: 0.7.5
source:
  git_url: https://github.com/ipa320/cob_simulation-release.git
  git_rev: release/noetic/cob_gazebo_worlds/0.7.5-1
  folder: ros-noetic-cob-gazebo-worlds/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 12
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-catkin
    - ros-noetic-cob-default-env-config
    - ros-noetic-roslaunch
    - ros-noetic-rostest
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-cob-default-env-config
    - ros-noetic-controller-manager
    - ros-noetic-gazebo-msgs
    - ros-noetic-gazebo-ros
    - ros-noetic-gazebo-ros-control
    - ros-noetic-joint-state-controller
    - ros-noetic-joint-state-publisher
    - ros-noetic-position-controllers
    - ros-noetic-robot-state-publisher
    - ros-noetic-rospy
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-velocity-controllers
    - ros-noetic-xacro
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
