package:
  name: ros-noetic-mbf-abstract-nav
  version: 0.4.0
source:
  git_url: https://github.com/uos-gbp/move_base_flex-release.git
  git_rev: release/noetic/mbf_abstract_nav/0.4.0-1
  folder: ros-noetic-mbf-abstract-nav/src/work

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 10
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-catkin
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-geometry-msgs
    - ros-noetic-mbf-abstract-core
    - ros-noetic-mbf-msgs
    - ros-noetic-mbf-utility
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - ros-noetic-xmlrpcpp
  run:
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-actionlib-msgs
    - ros-noetic-dynamic-reconfigure
    - ros-noetic-geometry-msgs
    - ros-noetic-mbf-abstract-core
    - ros-noetic-mbf-msgs
    - ros-noetic-mbf-utility
    - ros-noetic-nav-msgs
    - ros-noetic-roscpp
    - ros-noetic-std-msgs
    - ros-noetic-std-srvs
    - ros-noetic-tf
    - ros-noetic-xmlrpcpp
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
