package:
  name: ros-noetic-robot-calibration
  version: 0.6.4
source:
  git_url: https://github.com/ros-gbp/robot_calibration-release.git
  git_rev: release/noetic/robot_calibration/0.6.4-1
  folder: ros-noetic-robot-calibration/src/work
  patches:
    - patch/ros-noetic-robot-calibration.patch

build:
  script:
    sel(win): bld_catkin.bat
    sel(unix): build_catkin.sh
  number: 13
about:
  home: https://www.ros.org/
  license: BSD-3-Clause
  summary: |
    Robot Operating System

extra:
  recipe-maintainers:
    - ros-forge

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - "{{ compiler('c') }}"
    - ninja
    - sel(unix): make
    - sel(osx): tapi
    - cmake
    - sel(build_platform != target_platform): python
    - sel(build_platform != target_platform): cross-python_{{ target_platform }}
    - sel(build_platform != target_platform): cython
  host:
    - ceres-solver
    - gflags
    - libprotobuf
    - orocos-kdl
    - protobuf
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-camera-calibration-parsers
    - ros-noetic-catkin
    - ros-noetic-code-coverage
    - ros-noetic-control-msgs
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-kdl-parser
    - ros-noetic-moveit-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-pluginlib
    - ros-noetic-robot-calibration-msgs
    - ros-noetic-rosbag
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-visualization-msgs
    - suitesparse
  run:
    - ceres-solver
    - gflags
    - libprotobuf
    - orocos-kdl
    - protobuf
    - python
    - ros-distro-mutex 0.2 noetic
    - ros-noetic-actionlib
    - ros-noetic-camera-calibration-parsers
    - ros-noetic-control-msgs
    - ros-noetic-cv-bridge
    - ros-noetic-geometry-msgs
    - ros-noetic-kdl-parser
    - ros-noetic-moveit-msgs
    - ros-noetic-nav-msgs
    - ros-noetic-pluginlib
    - ros-noetic-robot-calibration-msgs
    - ros-noetic-rosbag
    - ros-noetic-roscpp
    - ros-noetic-sensor-msgs
    - ros-noetic-std-msgs
    - ros-noetic-tf
    - ros-noetic-tf2-geometry-msgs
    - ros-noetic-tf2-ros
    - ros-noetic-visualization-msgs
    - suitesparse
    - sel(osx and x86_64): __osx >={{ MACOSX_DEPLOYMENT_TARGET|default('10.14') }}
